# Customer Churn Prediction - Exploratory Data Analysis

## Objective
Understand the dataset before building the MLOps pipeline.

## Questions
- What is the target variable?
- What features are available?
- Are there missing values?
- Which columns are categorical?
- Which columns are numerical?
- What preprocessing will be required?

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("../data/customer_churn.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.shape

(7043, 21)

In [7]:
(df==" ").sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [8]:
df['TotalCharges'] = df['TotalCharges'].replace(" ",np.nan)

In [9]:
df = df.dropna(subset=["TotalCharges"])

In [10]:
df["TotalCharges"] = df["TotalCharges"].astype(float)

In [11]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [17]:
train_df = pd.read_csv("../artifacts/data_ingestion/train.csv")
test_df = pd.read_csv("../artifacts/data_ingestion/test.csv")

In [18]:
X_train = train_df.drop(columns=["Churn"])
y_train = train_df["Churn"]

X_test = test_df.drop(columns=["Churn"])
y_test = test_df["Churn"]

In [19]:
train_df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,4223-BKEOR,Female,0,No,Yes,21,Yes,No,DSL,Yes,...,Yes,No,No,Yes,One year,No,Mailed check,64.85,1336.8,No
1,6035-RIIOM,Female,0,No,No,54,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Two year,Yes,Bank transfer (automatic),97.20,5129.45,No
2,3797-VTIDR,Male,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,23.45,23.45,Yes
3,2568-BRGYX,Male,0,No,No,4,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.20,237.95,Yes
4,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [52]:
train_df["TotalCharges"] = pd.to_numeric(
    train_df["TotalCharges"],
    errors="coerce"
)

train_df = train_df.dropna()

In [53]:
test_df["TotalCharges"] = pd.to_numeric(
    test_df["TotalCharges"],
    errors="coerce"
)

test_df = test_df.dropna()

In [54]:
y_train = train_df["Churn"]

In [55]:
y_test = test_df["Churn"]

In [20]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5634 non-null   object
 1   gender            5634 non-null   object
 2   SeniorCitizen     5634 non-null   int64
 3   Partner           5634 non-null   object
 4   Dependents        5634 non-null   object
 5   tenure            5634 non-null   int64
 6   PhoneService      5634 non-null   object
 7   MultipleLines     5634 non-null   object
 8   InternetService   5634 non-null   object
 9   OnlineSecurity    5634 non-null   object
 10  OnlineBackup      5634 non-null   object
 11  DeviceProtection  5634 non-null   object
 12  TechSupport       5634 non-null   object
 13  StreamingTV       5634 non-null   object
 14  StreamingMovies   5634 non-null   object
 15  Contract          5634 non-null   object
 16  PaperlessBilling  5634 non-null   object
 17  PaymentMethod     5634 non-null   object
 18  MonthlyCharges    5634 non-null   float64
 19  TotalCharges      5634 non-null   object
 20  Churn             5634 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 924.5+ KB

In [21]:
train_df.describe(include="all")

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,5634,5634,5634.000000,5634,5634,5634.000000,5634,5634,5634,5634,...,5634,5634,5634,5634,5634,5634,5634,5634.000000,5634,5634
unique,5634,2,NaN,2,2,NaN,2,3,3,3,...,3,3,3,3,3,2,4,NaN,5300,2
top,4223-BKEOR,Male,NaN,No,No,NaN,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,20.2,No
freq,1,2887,NaN,2904,3951,NaN,5082,2685,2481,2810,...,2489,2791,2239,2223,3083,3325,1887,NaN,10,4138
mean,NaN,NaN,0.160809,NaN,NaN,32.373092,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.864253,NaN,NaN
std,NaN,NaN,0.367388,NaN,NaN,24.424539,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.089324,NaN,NaN
min,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,NaN,NaN
25%,NaN,NaN,0.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.750000,NaN,NaN
50%,NaN,NaN,0.000000,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.525000,NaN,NaN
75%,NaN,NaN,0.000000,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.937500,NaN,NaN
max,NaN,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.600000,NaN,NaN

In [22]:
X_train["TotalCharges"] = pd.to_numeric(
    X_train["TotalCharges"],
    errors="coerce"
)

In [23]:
X_test["TotalCharges"] = pd.to_numeric(
    X_test["TotalCharges"],
    errors="coerce"
)

In [24]:
X_train["TotalCharges"].isnull().sum()

np.int64(10)

In [25]:
X_train = X_train.dropna()

In [26]:
X_test = X_test.dropna()

In [32]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [43]:
num_pipeline = Pipeline(
    steps=[
        ("scaler", StandardScaler())
    ]
)

In [44]:
cat_pipeline = Pipeline(
    steps=[
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]
)

In [45]:
from sklearn.compose import ColumnTransformer

In [46]:
numerical_columns = X_train.select_dtypes(include="number").columns
categorical_columns = X_train.select_dtypes(include="object").columns

In [47]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", num_pipeline, numerical_columns),
        ("cat", cat_pipeline, categorical_columns)   
    ],
    remainder='passthrough'
)

In [48]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

In [49]:
print(type(X_train_transformed))
print(X_train_transformed.shape)

print(type(X_test_transformed))
print(X_test_transformed.shape)

<class 'scipy.sparse._csr.csr_matrix'>
(5624, 5669)
<class 'scipy.sparse._csr.csr_matrix'>
(1408, 5669)

In [56]:
print(y_train.shape)
print(y_test.shape)

(5624,)
(1408,)

In [57]:
y_train.head()

0     No
1     No
2    Yes
3    Yes
5     No
Name: Churn, dtype: object

In [58]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [59]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier,
    AdaBoostClassifier,
    ExtraTreesClassifier
)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

In [60]:
models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Extra Trees": ExtraTreesClassifier(),
    "KNN": KNeighborsClassifier(),
    "SVM": SVC()
}

In [61]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

import pandas as pd

In [64]:

def evaluate_model(model, X_train, y_train, X_test, y_test):

    # Train the model
    model.fit(X_train, y_train)

    # Make predictions
    y_pred = model.predict(X_test)

    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    return {
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1
    }

In [65]:
results = []

for name, model in models.items():

    scores = evaluate_model(
        model,
        X_train_transformed,
        y_train,
        X_test_transformed,
        y_test
    )

    scores["Model"] = name

    results.append(scores)

In [67]:
results_df = pd.DataFrame(results)

results_df = results_df[
    ["Model", "Accuracy", "Precision", "Recall", "F1 Score"]
]

results_df.sort_values(
    by="F1 Score",
    ascending=False
)

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.821733   0.687117  0.600536  0.640916
3    Gradient Boosting  0.811080   0.689046  0.522788  0.594512
7                  SVM  0.811080   0.690391  0.520107  0.593272
4             AdaBoost  0.802557   0.654723  0.538874  0.591176
6                  KNN  0.772727   0.573816  0.552279  0.562842
5          Extra Trees  0.799006   0.671756  0.471850  0.554331
2        Random Forest  0.788352   0.645914  0.445040  0.526984
1        Decision Tree  0.770597   0.585616  0.458445  0.514286